"""Ordinary DRF. No apiver imports, no apiver base classes, no apiver anything.

This is the file a developer already has in their project before adopting apiver, and
never touches again afterwards. If V2 serves V2-rooted links out of this file unchanged,
adoption is genuinely free for hyperlinks.
"""

from rest_framework import serializers
from rest_framework.reverse import reverse

from payments.models import Payment
from users.models import UserProfile


class PlainUserSerializer(serializers.HyperlinkedModelSerializer):
    """Nested inside the payment serializer below, to check nesting propagates."""

    class Meta:
        model = UserProfile
        fields = ["url", "username"]
        extra_kwargs = {"url": {"view_name": "userprofile-detail"}}


class PlainPaymentSerializer(serializers.HyperlinkedModelSerializer):
    """`url` is auto-generated by HyperlinkedModelSerializer — never declared here."""

    receipt_link = serializers.SerializerMethodField()

    class Meta:
        model = Payment
        fields = ["id", "url", "amount", "currency", "receipt_link"]

    def get_receipt_link(self, obj):
        """A bare reverse() call. Deliberately left un-helped, to size the residue."""
        return reverse(
            "payment-detail", kwargs={"pk": obj.pk}, request=self.context.get("request")
        )
