"""CLI seam (subprocess) for `apiver alias` (ticket #53, resolving ADR
0007's second amendment). `alias` declares a new `Alias` pointing at an
already-mounted version straight into the Aggregation Root — its
conventional home — with no separate `registry.py` and no schema/docs
wiring of its own (`Alias.urls` already re-includes the target's). Every
test runs against `tests/fixtures_mount/`, first mounting `v2` (via `apiver
mount`) so there is an already-mounted version to alias, then cleaning up
whatever both commands generated afterwards.
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_ROOT = REPO_ROOT / "tests" / "fixtures_mount"
API_DIR = FIXTURE_ROOT / "api"
AGGREGATION_ROOT = API_DIR / "urls.py"

# Directories that ship as part of the fixture, never generated by a test —
# anything else found under api/ after a test ran is `mount`'s own output.
_FIXTURE_ENTRIES = {"v0", "v1", "v1_0_0", "d2026_01_01", "notaversion", "__init__.py", "__pycache__"}


def _run(
    command: str, *args: str, settings: str = "tests.fixtures_mount.settings"
) -> subprocess.CompletedProcess:
    env = dict(os.environ)
    env["DJANGO_SETTINGS_MODULE"] = settings
    env["PYTHONPATH"] = os.pathsep.join([str(REPO_ROOT / "src"), str(REPO_ROOT)])
    return subprocess.run(
        [sys.executable, "-m", "apiver.cli", command, *args],
        cwd=str(REPO_ROOT),
        env=env,
        capture_output=True,
        text=True,
    )


@pytest.fixture(autouse=True)
def _clean_generated_output():
    AGGREGATION_ROOT.unlink(missing_ok=True)
    yield
    AGGREGATION_ROOT.unlink(missing_ok=True)
    for child in API_DIR.iterdir():
        if child.name not in _FIXTURE_ENTRIES:
            shutil.rmtree(child)


def _mount_v2() -> None:
    result = _run("mount", "v2", "--from", "v1")
    assert result.returncode == 0, result.stderr


def test_alias_declares_an_alias_pointing_at_the_mounted_version():
    _mount_v2()

    result = _run("alias", "stable", "--from", "v2")

    assert result.returncode == 0, result.stderr
    assert f"wrote {AGGREGATION_ROOT}" in result.stdout
    assert "add 'stable' to APIVER_ALIASES" in result.stdout

    source = AGGREGATION_ROOT.read_text()
    assert "from apiver.drf import Alias" in source
    assert "stable = Alias('stable', target=v2)" in source
    assert "    path('api/stable/', stable.urls)," in source
    # No include() wrapper — Alias.urls already returns one.
    assert "include(stable.urls)" not in source


def test_alias_refuses_a_from_that_is_not_mounted():
    _mount_v2()

    result = _run("alias", "stable", "--from", "v1")

    assert result.returncode != 0
    assert "not mounted" in result.stderr
    assert "stable" not in AGGREGATION_ROOT.read_text()


def test_alias_refuses_a_from_with_no_registry_py():
    _mount_v2()

    result = _run("alias", "stable", "--from", "vnothing")

    assert result.returncode != 0
    assert "could not be imported" in result.stderr
    assert "stable" not in AGGREGATION_ROOT.read_text()


def test_alias_refuses_a_from_that_is_not_a_version_instance():
    _mount_v2()

    result = _run("alias", "stable", "--from", "notaversion")

    assert result.returncode != 0
    assert "is not a Version instance" in result.stderr
    assert "stable" not in AGGREGATION_ROOT.read_text()


def test_alias_refuses_a_from_naming_another_alias():
    _mount_v2()

    result = _run("alias", "stable", "--from", "already_alias")

    assert result.returncode != 0
    assert "cannot target another alias" in result.stderr
    assert "stable" not in AGGREGATION_ROOT.read_text()


def test_alias_refuses_to_collide_with_an_already_mounted_version_name():
    _mount_v2()

    result = _run("alias", "v2", "--from", "v2")

    assert result.returncode != 0
    assert "already mounted" in result.stderr


def test_alias_refuses_to_declare_the_same_alias_twice():
    _mount_v2()
    first = _run("alias", "stable", "--from", "v2")
    assert first.returncode == 0, first.stderr
    written = AGGREGATION_ROOT.read_text()

    second = _run("alias", "stable", "--from", "v2")

    assert second.returncode != 0
    assert "already mounted" in second.stderr
    assert AGGREGATION_ROOT.read_text() == written


def test_alias_extends_an_aggregation_root_that_already_has_an_alias():
    _mount_v2()
    first = _run("alias", "stable", "--from", "v2")
    assert first.returncode == 0, first.stderr

    second = _run("alias", "latest", "--from", "v2")

    assert second.returncode == 0, second.stderr
    source = AGGREGATION_ROOT.read_text()
    # The Alias import is only ever appended once.
    assert source.count("from apiver.drf import Alias") == 1
    assert "stable = Alias('stable', target=v2)" in source
    assert "latest = Alias('latest', target=v2)" in source
    assert "    path('api/stable/', stable.urls)," in source
    assert "    path('api/latest/', latest.urls)," in source


def test_alias_refuses_a_scheme_nonconforming_from():
    """ticket #67, ADR 0008 item 5: `--from` is validated against the
    configured scheme even though it already resolves to a real, mounted
    Version — modeling a project that mounted 'v2' under `sequential` and
    only later switched APIVER_VERSION_SCHEME to `semver`, under which
    'v2' no longer conforms."""
    _mount_v2()

    result = _run("alias", "stable", "--from", "v2", settings="tests.fixtures_mount.settings_semver")

    assert result.returncode != 0
    assert "--from 'v2' does not conform" in result.stderr
    assert "APIVER_VERSION_SCHEME='semver'" in result.stderr
    assert "stable" not in AGGREGATION_ROOT.read_text()


def test_alias_name_stays_exempt_from_scheme_validation():
    """ADR 0008 item 5: an alias name is a human label ('stable'), not a
    version point — it's never checked against the scheme, even a strict
    one under which it could never conform, and its own literal URL
    segment keeps that raw name, unformatted."""
    mounted = _run("mount", "v1_1_0", "--from", "v1_0_0", settings="tests.fixtures_mount.settings_semver")
    assert mounted.returncode == 0, mounted.stderr

    result = _run("alias", "stable", "--from", "v1_1_0", settings="tests.fixtures_mount.settings_semver")

    assert result.returncode == 0, result.stderr
    source = AGGREGATION_ROOT.read_text()
    assert "stable = Alias('stable', target=v1_1_0)" in source
    assert "    path('api/stable/', stable.urls)," in source


def test_alias_requires_the_from_flag():
    _mount_v2()

    result = _run("alias", "stable")

    assert result.returncode != 0
    assert "--from" in result.stderr


def test_alias_defaults_the_root_dir_when_apiver_root_dir_is_unset(tmp_path):
    """APIVER_ROOT_DIR unset now falls back to "apiversions" (ADR 0003's
    ticket #77 amendment) instead of refusing outright — but this fixture
    project's v2 lives under "tests.fixtures_mount.api", not "apiversions",
    so --from v2 still fails to import, just for a different reason. Run
    with cwd=tmp_path: alias also resolves the (now-defaulted) root dir
    before failing, and any incidental filesystem side effect must never
    land in the real repo."""
    _mount_v2()
    (tmp_path / "settings_no_root_dir.py").write_text(
        "from tests.fixtures_mount.settings import *  # noqa: F403\nAPIVER_ROOT_DIR = None\n"
    )
    env = dict(os.environ)
    env["DJANGO_SETTINGS_MODULE"] = "settings_no_root_dir"
    env["PYTHONPATH"] = os.pathsep.join([str(REPO_ROOT / "src"), str(REPO_ROOT), str(tmp_path)])

    result = subprocess.run(
        [sys.executable, "-m", "apiver.cli", "alias", "stable", "--from", "v2"],
        cwd=str(tmp_path),
        env=env,
        capture_output=True,
        text=True,
    )

    assert result.returncode != 0
    assert "apiversions.v2.registry" in result.stderr


def test_alias_requires_django_settings_module():
    env = dict(os.environ)
    env.pop("DJANGO_SETTINGS_MODULE", None)
    env["PYTHONPATH"] = os.pathsep.join([str(REPO_ROOT / "src"), str(REPO_ROOT)])

    result = subprocess.run(
        [sys.executable, "-m", "apiver.cli", "alias", "stable", "--from", "v2"],
        cwd=str(REPO_ROOT),
        env=env,
        capture_output=True,
        text=True,
    )

    assert result.returncode != 0
    assert "DJANGO_SETTINGS_MODULE" in result.stderr
