"""CLI seam (subprocess) for `apiver mount` (ticket 43, ADR 0007 item 7;
redesigned by ticket #47). `mount` is the only way a new, authored version
comes into existence: it generates `registry.py` from scratch — derived
from `--from`, with its own schema/docs routes already wired — then
appends its `include()` to the Aggregation Root. Every test runs against
`tests/fixtures_mount/` — a project with only `v0`/`v1` pre-authored (v0
has neither schema nor docs of its own; v1 has a schema route but no
docs) and no aggregation root yet — and cleans up whatever `mount` itself
generated afterwards.
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_ROOT = REPO_ROOT / "tests" / "fixtures_mount"
API_DIR = FIXTURE_ROOT / "api"
AGGREGATION_ROOT = API_DIR / "urls.py"
V2_REGISTRY = API_DIR / "v2" / "registry.py"

# Directories that ship as part of the fixture, never generated by a test —
# anything else found under api/ after a test ran is `mount`'s own output.
# v1_0_0/d2026_01_01 are pre-authored `--from` sources for the semver/date
# scheme-conformance tests below (ticket #67) — mount itself now refuses to
# author a non-conforming slug, so exercising those schemes' happy path
# needs an existing, already-conforming source to derive from.
_FIXTURE_ENTRIES = {"v0", "v1", "v1_0_0", "d2026_01_01", "notaversion", "__init__.py", "__pycache__"}


def _run(*args: str, settings: str = "tests.fixtures_mount.settings") -> subprocess.CompletedProcess:
    env = dict(os.environ)
    env["DJANGO_SETTINGS_MODULE"] = settings
    env["PYTHONPATH"] = os.pathsep.join([str(REPO_ROOT / "src"), str(REPO_ROOT)])
    return subprocess.run(
        [sys.executable, "-m", "apiver.cli", "mount", *args],
        cwd=str(REPO_ROOT),
        env=env,
        capture_output=True,
        text=True,
    )


@pytest.fixture(autouse=True)
def _clean_generated_output():
    AGGREGATION_ROOT.unlink(missing_ok=True)
    yield
    AGGREGATION_ROOT.unlink(missing_ok=True)
    for child in API_DIR.iterdir():
        if child.name not in _FIXTURE_ENTRIES:
            shutil.rmtree(child)


def test_mount_generates_a_new_versions_registry_py_from_scratch():
    """The developer hand-writes nothing — `mount` creates v2/registry.py
    itself: derived from v1, with its own schema route wired (v1 already
    has one to inherit the key from) and its own docs route wired too
    (v1 has none, so this is a fresh register(), not an override) —
    every version gets both, unconditionally (ticket #47)."""
    result = _run("v2", "--from", "v1")

    assert result.returncode == 0, result.stderr
    assert f"wrote {V2_REGISTRY}" in result.stdout
    assert f"wrote {AGGREGATION_ROOT}" in result.stdout
    assert "add 'v2' to APIVER_VERSIONS" in result.stdout

    source = V2_REGISTRY.read_text()
    assert "from tests.fixtures_mount.api.v1.registry import v1" in source
    assert "v2 = v1.derive('v2')" in source
    assert "v2.override('schema/', v2.schema_view(prefix='api/v2/'), name='schema')" in source
    assert "v2.register('docs/', v2.docs_view(), name='docs')" in source

    aggregation_source = AGGREGATION_ROOT.read_text()
    assert "from tests.fixtures_mount.api.v2.registry import v2" in aggregation_source
    assert "    path('api/v2/', include(v2.urls))," in aggregation_source


def test_mount_wires_register_for_both_when_the_source_has_neither():
    """v0 has no schema and no docs of its own — v9, derived from it,
    still gets both wired, via register() rather than override() since
    neither key resolves anywhere in v0's chain."""
    result = _run("v9", "--from", "v0")

    assert result.returncode == 0, result.stderr
    source = (API_DIR / "v9" / "registry.py").read_text()
    assert "v9.register('schema/', v9.schema_view(prefix='api/v9/'), name='schema')" in source
    assert "v9.register('docs/', v9.docs_view(), name='docs')" in source


def test_mount_refuses_if_registry_py_already_exists():
    first = _run("v2", "--from", "v1")
    assert first.returncode == 0, first.stderr
    written = V2_REGISTRY.read_text()

    second = _run("v2", "--from", "v1")

    assert second.returncode != 0
    assert "already exists" in second.stderr
    assert V2_REGISTRY.read_text() == written


def test_mount_refuses_a_from_with_no_registry_py():
    result = _run("v2", "--from", "vnothing")

    assert result.returncode != 0
    assert "could not be imported" in result.stderr
    assert not V2_REGISTRY.exists()
    assert not AGGREGATION_ROOT.exists()


def test_mount_refuses_a_from_that_is_not_a_version_instance():
    result = _run("v2", "--from", "notaversion")

    assert result.returncode != 0
    assert "is not a Version instance" in result.stderr
    assert not V2_REGISTRY.exists()
    assert not AGGREGATION_ROOT.exists()


def test_mount_requires_the_from_flag():
    result = _run("v2")

    assert result.returncode != 0
    assert "--from" in result.stderr
    assert not V2_REGISTRY.exists()


def test_mount_extends_an_existing_aggregation_root():
    first = _run("v2", "--from", "v1")
    assert first.returncode == 0, first.stderr

    second = _run("v9", "--from", "v1")

    assert second.returncode == 0, second.stderr
    source = AGGREGATION_ROOT.read_text()
    assert "from tests.fixtures_mount.api.v2.registry import v2" in source
    assert "from tests.fixtures_mount.api.v9.registry import v9" in source
    assert "    path('api/v2/', include(v2.urls))," in source
    assert "    path('api/v9/', include(v9.urls))," in source


def test_mount_refuses_to_mount_the_same_version_twice():
    first = _run("v2", "--from", "v1")
    assert first.returncode == 0, first.stderr
    shutil.rmtree(API_DIR / "v2")  # only the registry.py already-exists check would otherwise fire first
    written = AGGREGATION_ROOT.read_text()

    second = _run("v2", "--from", "v1")

    assert second.returncode != 0
    assert "already mounted" in second.stderr
    assert AGGREGATION_ROOT.read_text() == written


def test_mount_requires_apiver_root_dir(tmp_path):
    (tmp_path / "settings_no_root_dir.py").write_text(
        "from tests.fixtures_mount.settings import *  # noqa: F403\nAPIVER_ROOT_DIR = None\n"
    )
    env = dict(os.environ)
    env["DJANGO_SETTINGS_MODULE"] = "settings_no_root_dir"
    env["PYTHONPATH"] = os.pathsep.join([str(REPO_ROOT / "src"), str(REPO_ROOT), str(tmp_path)])

    result = subprocess.run(
        [sys.executable, "-m", "apiver.cli", "mount", "v2", "--from", "v1"],
        cwd=str(REPO_ROOT),
        env=env,
        capture_output=True,
        text=True,
    )

    assert result.returncode != 0
    assert "APIVER_ROOT_DIR" in result.stderr
    assert not AGGREGATION_ROOT.exists()


def test_mount_refuses_a_scheme_nonconforming_version_name():
    """ticket #67, ADR 0008 item 5: under the default `sequential` scheme,
    'v1a' is a valid Python identifier but not a valid slug (its base
    isn't all digits) — mount must refuse it before writing anything,
    exactly like its existing identifier check."""
    result = _run("v1a", "--from", "v1")

    assert result.returncode != 0
    assert "does not conform" in result.stderr
    assert "APIVER_VERSION_SCHEME='sequential'" in result.stderr
    assert not (API_DIR / "v1a").exists()
    assert not AGGREGATION_ROOT.exists()


def test_mount_refuses_a_scheme_nonconforming_from():
    """--from is validated too (ADR 0008 item 5): under `semver`, 'v1' is a
    real, already-mounted-able Version but doesn't conform to the
    configured scheme's shape."""
    result = _run("v1_1_0", "--from", "v1", settings="tests.fixtures_mount.settings_semver")

    assert result.returncode != 0
    assert "--from 'v1' does not conform" in result.stderr
    assert "APIVER_VERSION_SCHEME='semver'" in result.stderr
    assert not (API_DIR / "v1_1_0").exists()
    assert not AGGREGATION_ROOT.exists()


def test_mount_uses_display_name_in_generated_urls_under_semver_scheme():
    """ADR 0008 item 7: the literal URL path segment carries the Scheme's
    Display Name ('v1.1.0'), while the module dotted path, the instance
    namespace (the bare `v1_1_0` identifier), and schema_view's Python-side
    call keep the raw slug — only the string literal changes."""
    result = _run("v1_1_0", "--from", "v1_0_0", settings="tests.fixtures_mount.settings_semver")

    assert result.returncode == 0, result.stderr
    registry_source = (API_DIR / "v1_1_0" / "registry.py").read_text()
    assert "from tests.fixtures_mount.api.v1_0_0.registry import v1_0_0" in registry_source
    assert "v1_1_0 = v1_0_0.derive('v1_1_0')" in registry_source
    assert (
        "v1_1_0.register('schema/', v1_1_0.schema_view(prefix='api/v1.1.0/'), name='schema')"
        in registry_source
    )

    aggregation_source = AGGREGATION_ROOT.read_text()
    assert "from tests.fixtures_mount.api.v1_1_0.registry import v1_1_0" in aggregation_source
    assert "    path('api/v1.1.0/', include(v1_1_0.urls))," in aggregation_source


def test_mount_uses_display_name_in_generated_urls_under_date_scheme():
    result = _run("d2026_08_11", "--from", "d2026_01_01", settings="tests.fixtures_mount.settings_date")

    assert result.returncode == 0, result.stderr
    registry_source = (API_DIR / "d2026_08_11" / "registry.py").read_text()
    assert "d2026_08_11 = d2026_01_01.derive('d2026_08_11')" in registry_source
    assert (
        "d2026_08_11.register('schema/', d2026_08_11.schema_view(prefix='api/2026-08-11/'), "
        "name='schema')" in registry_source
    )

    aggregation_source = AGGREGATION_ROOT.read_text()
    assert "    path('api/2026-08-11/', include(d2026_08_11.urls))," in aggregation_source


def test_mount_requires_django_settings_module():
    env = dict(os.environ)
    env.pop("DJANGO_SETTINGS_MODULE", None)
    env["PYTHONPATH"] = os.pathsep.join([str(REPO_ROOT / "src"), str(REPO_ROOT)])

    result = subprocess.run(
        [sys.executable, "-m", "apiver.cli", "mount", "v2", "--from", "v1"],
        cwd=str(REPO_ROOT),
        env=env,
        capture_output=True,
        text=True,
    )

    assert result.returncode != 0
    assert "DJANGO_SETTINGS_MODULE" in result.stderr
