# Generated by Django 6.1 on 2026-08-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('event_type', models.CharField(choices=[('payment.completed', 'Payment completed'), ('order.created', 'Order created'), ('order.cancelled', 'Order cancelled')], max_length=50)),
                ('secret', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
