"""Generated by `apiver migrate`; extended in place by `apiver mount`
as later versions are authored (ADR 0007 item 2). Hand-editable in
between — apiver only ever appends a new version's mount here, never
rewrites an existing line."""

from django.urls import include, path

from api.v1.registry import v1

urlpatterns = [
    path('api/v1/', include(v1.urls)),
]
