"""Generated by `apiver init`; extended in place by `apiver mount`
as later versions are authored (ADR 0007 item 2). Hand-editable in
between — apiver only ever appends a new version's mount here, never
rewrites an existing line."""

from django.urls import include, path

from tests.fixtures_remove.api.v1.registry import v1
from tests.fixtures_remove.api.v2.registry import v2
from tests.fixtures_remove.api.v10.registry import v10
from tests.fixtures_remove.api.v11.registry import v11
from tests.fixtures_remove.api.v12.registry import v12
from tests.fixtures_remove.api.v20.registry import v20
from tests.fixtures_remove.api.v21.registry import v21
from tests.fixtures_remove.api.v30.registry import v30
from tests.fixtures_remove.api.v31.registry import v31
from tests.fixtures_remove.api.v40.registry import v40

urlpatterns = [
    path("api/v1/", include(v1.urls)),
    path("api/v2/", include(v2.urls)),
    path("api/v10/", include(v10.urls)),
    path("api/v11/", include(v11.urls)),
    path("api/v12/", include(v12.urls)),
    path("api/v20/", include(v20.urls)),
    path("api/v21/", include(v21.urls)),
    path("api/v30/", include(v30.urls)),
    path("api/v31/", include(v31.urls)),
    path("api/v40/", include(v40.urls)),
]
